# Generated by Django 5.1 on 2024-08-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия заказчика')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Самовывоз'), ('CR', 'Курьер')], default='SH', max_length=2, verbose_name='Способ доставки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('finish', models.BooleanField(default=False, verbose_name='Выполнено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон компании')),
                ('address_company', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(max_length=255, verbose_name='Город отгрузки')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность к заказу')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование позиции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('size', models.PositiveIntegerField(default=36, verbose_name='Размер')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления на сайт')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность к заказу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.category', verbose_name='Категория')),
                ('collection', models.ManyToManyField(blank=True, null=True, to='shoes_shop.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обуви',
            },
        ),
        migrations.CreateModel(
            name='PosSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество пар')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.shoes', verbose_name='Позиция обуви')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество пар')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на позицию')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.order', verbose_name='Заказ')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.shoes', verbose_name='Позиция обуви')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shoe',
            field=models.ManyToManyField(through='shoes_shop.PosOrder', to='shoes_shop.shoes', verbose_name='Позиция обуви'),
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(verbose_name='Дата поставки')),
                ('shoe', models.ManyToManyField(through='shoes_shop.PosSupply', to='shoes_shop.shoes', verbose_name='Товары')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='possupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes_shop.supply', verbose_name='Поставка'),
        ),
    ]
